[package]
name = "bpf2"
version = "0.1.0"
authors = ["Tamas Levai <levait@tmit.bme.hu>"]

[dependencies]
e2d2 = { path = "../../framework", features = ["performance"] }
time = "=0.1.36"
getopts = "*"
rand = "0.3.15"
fnv = "*"
twox-hash = "*"
redis = "=0.8.0"

[features]
default = []
print = []
